### PR TITLE
elevation plot size reduced!

### PR DESCRIPTION
**Pull request by stefanovic80**
Hi, I believe a smaller size of the elevation plot makes things much more readable. For this reason I've replaced the line of code

elevation.layout.min_height = 'auto' 

with 

elevation.layout.min_height = '300px'

As you probability can see from your own. Despite I am not a complete new git/github user, this job is meant to be my first pull request ever. Hopefully it's a usefull improvement of your project and it's the begining for further collaborations...

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @stefanovic80 for this change, it looks good :+1:  And congrats on your first contribution!

The diff shows that some outputs have been added to the notebook. Would you mind clearing them up, for example by clicking on "Restart kernel and Clear all outputs" in the JupyterLab menu?

**Comment by stefanovic80** [comment]
I meant to change not more than that "auto" with a "300px" in order to make the plot smaller in hight and from my experiments it works fine. Further differences may come up from three reasons:
1) I added at least one further cell at the beginning in order to try further improvements, but I removed them before hand as I considered them useless
2) For sure I did a "Restart kernel and Clear all outputs" at least one time
3) I probability have done some some meaningless changes in the "base" environment before running it again on the right one (I'm still not very familiar with environments!) and, from my understanding, that may have provided some further modifications into the .yml file

But still I do not find any issue while testing it. Please, let me know if you accept it as it is or you may suggest me to make a new pull request

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
btw @stefanovic80 you might want to add the email address used for the commits to your GitHub account so your contributions appear correctly: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

**Pull request merged**
